from moodownloader.authentication.infrastructure.authenticator import MoodleAuthenticator
from moodownloader.course_management.infrastructure.navigator import MoodleNavigator
from moodownloader.course_management.infrastructure.downloader import PdfDownloader